NOTICE, ionic.project, www/css/ionic.app.css, www/css/style.css, www/index.html, www/js/core/main.js
- Adding license in main, and app.js
- Adding NOTICE file required with Apache licensing
- Setup project with SASS
...
=> More basic set up for the app

gulpfile.js, ionic.project, package.json, www/app.js, www/build/mm.bundle.js, www/core/main.js, www/index.html
Rebased on https://github.com/moodlehq/moodlemobile2/pull/1/commits
Diff: https://github.com/FMCorz/moodlemobile2/compare/scaffold...FMCorz:gulp-build?expand=1
=> MOBILE-817 gulp: Concatenating JS files

www/app.js, www/core/components/README, www/core/lang/README, www/core/lib/README, www/index.html
Added some missing directories with tmp files.
=> MOBILE-778 core: Directory structure

www/build/lang/en.json, www/build/mm.bundle.js, www/core/lang/en.json, www/core/lib/util.js
=> MOBILE-979 $mmUtil: Incorrect language key used for error modal title

www/addons/participants/services/participants.js, www/addons/participants/templates/list.html, www/build/mm.bundle.js, www/core/lib/site.js
=> Mobile 985

www/addons/files/services/helper.js, www/build/mm.bundle.js, www/core/lib/app.js, www/core/lib/db.js, www/core/lib/filepool.js, www/core/lib/fs.js, www/core/lib/site.js, www/core/lib/sitesmanager.js, www/core/lib/util.js, www/core/lib/ws.js
=> Mobile 1014 rebased

www/core/lib/lang.js
This reverts commit 6977890c07c9bc1abcb98b5d59793a65539f37f0, reversing
changes made to acb63b6e907716b99314e872e9f33ef4d21045bb.
=> Revert "Merge pull request #198 from dpaloucva/MOBILE-1190"

www/addons/competency/templates/competency.html, www/addons/competency/templates/coursecompetencies.html
This reverts commit f1aedf7ff61a0fd63c08c0ef17557feb9e52f1e0.
=> MOBILE-1596 cbe: Show activity icons

gulpfile.js
This commit also try fix the indentation of the
e2e/build/protractor.conf.js file
=> MOBILE-1684 e2e: Increase page time out for travis

upgrade.txt, www/config.json, www/core/components/settings/controllers/about.js, www/core/components/settings/lang/ca.json, www/core/components/settings/lang/cs.json, www/core/components/settings/lang/da.json, www/core/components/settings/lang/de.json, www/core/components/settings/lang/en.json, www/core/components/settings/lang/es-mx.json, www/core/components/settings/lang/es.json, www/core/components/settings/lang/eu.json, www/core/components/settings/lang/fr.json, www/core/components/settings/lang/it.json, www/core/components/settings/lang/nl.json, www/core/components/settings/lang/pt-br.json, www/core/components/settings/lang/pt.json, www/core/components/settings/lang/ro.json, www/core/components/settings/lang/ru.json, www/core/components/settings/lang/sv.json, www/core/components/settings/templates/about.html
Removing it from language file
=> MOBILE-1765 settings: App name should be part of config.json

www/core/components/login/lang/en.json
Fixes for other languages must be done via AMOS (lang.moodle.net)
=> MOBILE-1885 login: Fix the help me login text

www/addons/messages/controllers/discussion.js, www/addons/messages/main.js, www/addons/messages/services/handlers.js, www/addons/messages/templates/discussion.html, www/core/directives/autofocus.js
=> MOBILE-1904 keyboard: Do not display in conversation

src/core/course/components/format/format.ts, src/core/course/components/module/module.ts
Update the section download icon to reflect changes to the download state
of modules within the section, either from the download buttons on the
course page or activity within the module.
=> MOBILE-3054 Courses: Update section download icon

src/addon/mod/survey/providers/helper.ts
This was a regression caused by MOBILE-3109
=> MOBILE-3247 survey: Fix issues with last 2 questions in survey

src/addon/mod/book/components/index/addon-mod-book-index.html, src/addon/mod/book/components/index/index.ts, src/addon/mod/folder/components/index/index.ts, src/addon/mod/imscp/components/index/addon-mod-imscp-index.html, src/addon/mod/imscp/components/index/index.ts, src/addon/mod/page/components/index/addon-mod-page-index.html, src/addon/mod/page/components/index/index.ts, src/addon/mod/resource/components/index/addon-mod-resource-index.html, src/addon/mod/resource/components/index/index.ts, src/addon/mod/url/components/index/index.ts, src/core/course/classes/main-activity-component.ts, src/core/course/classes/main-resource-component.ts, src/core/course/providers/module-prefetch-delegate.ts
Also, now the download function is called only if it's really needed
=> MOBILE-3375 course: Make download warnings less intrusive

package-lock.json, src/providers/utils/iframe.ts
This fixes the code that will be broken once https://github.com/moodlemobile/cordova-plugin-wkuserscript/pull/1 is merged.
=> MOBILE-3320 plugins: Update wkuserscript plugin usage

src/core/login/pages/credentials/credentials.html, src/core/login/pages/reconnect/reconnect.html
For allowing users to use Google Smart Lock and shared web credentials for iOS
=> MOBILE-3587 login: Support auto-complete

.github/workflows/e2e.yml, src/core/classes/page-items-list-manager.ts, src/core/features/courses/components/course-progress/core-courses-course-progress.html, src/core/features/courses/lang.json
There are a couple of commits here that are not directly related with tests, but I found them by writing Behat tests so I think it's ok to include them in this PR.
=> MOBILE-3738: Migrate Behat tests to ionic 5

src/index.html
The CSP is only used in the webapp
=> MOBILE-3863 index: Make CSP less strict

.github/workflows/performance.yml, scripts/print-measure-timings.js, tests/behat/behat_performance.php, tests/behat/classes/measure_timing.php, tests/behat/performance.feature
The new Performance action will not work until the following PR is merged: https://github.com/moodlehq/moodle-local_moodlemobileapp/pull/32
=> MOBILE-3875 ci: Configure performance tests

package-lock.json, package.json
As discussed in https://github.com/havesource/cordova-plugin-push/pull/176, the previous configuration was not entirely correct.
=> MOBILE-3833 pushnotifications: Update plugin

src/core/components/local-file/local-file.ts, src/core/directives/link.ts, src/core/features/course/services/course-helper.ts, src/core/services/file-helper.ts, src/core/services/utils/dom.ts, src/core/services/utils/iframe.ts, src/core/singletons/window.ts, src/tests/behat/open_files.feature
Blocked by [MDL-74816](https://tracker.moodle.org/browse/MDL-74816)
=> MOBILE-4054 core: Allow not displaying again open file warning

src/core/features/grades/tests/behat/navigation.feature, src/core/features/mainmenu/components/user-menu-button/user-menu-button.html, src/core/features/mainmenu/components/user-menu-button/user-menu-button.ts, src/core/features/mainmenu/pages/menu/menu.html
This shouldn't be merged until [MDL-74613](https://tracker.moodle.org/browse/MDL-74613) is resolved.
=> MOBILE-4069 grades: Implement navigation tests

src/core/features/courses/courses-lazy.module.ts, src/core/features/courses/services/courses-helper.ts
This solve black ion-toolbar after use QR scanner too.
=> MOBILE-4081 courses: Load 'my.module' from service

src/addons/competency/tests/behat/navigation.feature
This shouldn't be merged until [MDL-74655](https://tracker.moodle.org/browse/MDL-74655) is resolved.
=> MOBILE-4069 competency: Implement navigation tests

src/addons/mod/feedback/tests/behat/navigation.feature
This shouldn't be merged until [MDL-72178](https://tracker.moodle.org/browse/MDL-72178) is resolved.
=> MOBILE-4069 feedback: Implement navigation tests

local_moodleappbehat/tests/behat/behat_app.php, src/core/features/comments/tests/behat/basic_usage.feature, src/core/features/course/tests/behat/basic_usage-311.feature, src/core/features/course/tests/behat/basic_usage.feature, src/core/features/courses/tests/behat/basic_usage-310.feature, src/core/features/courses/tests/behat/basic_usage-311.feature, src/core/features/courses/tests/behat/basic_usage.feature, src/theme/theme.base.scss
This shouldn't be merged until [MDL-75353](https://tracker.moodle.org/browse/MDL-75353) is resolved.
=> MOBILE-4081: Behat improvements

package-lock.json, package.json
This fixes a crash when using local notifications with target 31
=> MOBILE-4123 cordova: Update local-notifications plugin

src/addons/mod/data/tests/behat/entries.feature, src/addons/mod/data/tests/behat/sync.feature
Same as https://github.com/moodle/moodle/commit/aa49eb24fb14dfd07cd20b3361adc8918e6ffa82
=> MOBILE-4081 behat: Fix database tests

src/core/features/mainmenu/pages/menu/menu.ts, src/core/features/settings/classes/settings-handlers-source.ts, src/core/features/settings/pages/site/site.html, src/core/features/settings/pages/site/site.ts, src/core/features/settings/services/settings-delegate.ts, src/core/singletons/events.ts
This pull request has the following two changes:
- Add possibility of add toggle inside site preferences page.
- Add event to use it when main home loads.
=> Mobile 4081

package.json
This new version includes the permission to schedule alarms
=> MOBILE-4118 core: Update local-notifications plugin

package-lock.json, package.json
This version fixes clicks in notifications in Android 12
=> MOBILE-4090 core: Update local-notifications plugin to .6

package-lock.json, package.json
This version fixes duplicated Activity when clicking a notification.
=> MOBILE-4090 core: Update local-notifications plugin to .7

src/core/features/grades/pages/course/course.html, src/core/features/grades/pages/course/course.page.ts, src/core/features/grades/pages/course/course.scss, src/core/features/grades/services/grades-helper.ts
Fixes some breaking changes introduced in MDL-75513. The fixes included here are not exhaustive but should take care of the basic scenarios covered by e2e tests. Subsequent fixes will be provided to handle other edge-cases.
=> MOBILE-4176 grades: Fix 4.1 layout

package-lock.json
Update produced running `npx browserslist@latest --update-db`
=> MOBILE-4081 npm: Update caniuse versions

scripts/langindex.json, src/core/features/course/components/module-summary/module-summary.html, src/core/features/grades/lang.json
=> MOBILE-4081 core: Translate hard-coded string

src/core/classes/site.ts, src/core/services/database/sites.ts
This commit reverts most of the changes done in https://github.com/moodlehq/moodleapp/pull/3339/commits/e63a40d0925f8c31dfa2aafea107d7698ede1612
=> MOBILE-4081 core: Revert split wscache into several tables

scripts/langindex.json, src/core/features/login/pages/site/site.ts, src/core/features/login/tests/behat/basic_usage.feature, src/core/lang.json, src/core/services/utils/dom.ts
String dropped in favour of core.cannotconnect
=> MOBILE-4301 core: Drop core.sitenotfound string

src/core/features/course/components/course-format/course-format.ts, src/core/features/course/components/course-index/course-index.ts
Including the ones that were previously hidden, such as text and label.
=> MOBILE-4277 course: Show modules in course index

src/addons/calendar/services/calendar.ts
This schedules their default reminder if it's a new event
=> MOBILE-4317 calendar: Store events from getEventsList in DB

src/core/classes/items-management/items-manager.ts, src/core/classes/items-management/list-items-manager.ts, src/core/classes/items-management/routed-items-manager.ts, src/core/classes/tests/swipe-navigation-items-manager.test.ts, src/core/components/split-view/split-view.ts, src/core/singletons/dom.ts
Scroll to current element when swipe in split-view page.
=> [4.2] MOBILE-4202 split-view: Scroll to current element when swipe

src/core/features/course/classes/main-resource-component.ts
This is a temporary solution, the code that handles automatic activity completion should be refactored
=> MOBILE-4275 course: Fix course completion not updated in some cases

src/addons/mod/assign/components/submission/submission.ts
Similar to https://github.com/moodle/moodle/commit/9eb1e4d7c0bd05341ef8aa2df38195ffa56fba53
=> MOBILE-4382 assign: Use granted extensions on remaining time

package-lock.json, package.json
This will allow inspecting the WebView in iOS devices (debug builds)
=> MOBILE-4398 core: Update webview plugin to 5.0.0-moodle.2

src/core/features/courses/services/courses.ts
Otherwise an error is displayed in console when trying to use the WS
=> MOBILE-4367 courses: Check if core_my_view_page is available

src/core/features/user/pages/profile/profile.html, src/core/features/user/pages/profile/profile.ts
This reverts commit e4081e6c1a949376096eccaee4b63b2b0c90f767.
=> Revert "MOBILE-4242 profile: Add groups to participants profile"

scripts/langindex.json, src/addons/mod/quiz/lang.json, src/addons/mod/quiz/pages/player/player.ts, src/addons/mod/quiz/tests/behat/basic_usage-311.feature, src/addons/mod/quiz/tests/behat/basic_usage-39.feature, src/addons/mod/quiz/tests/behat/basic_usage.feature, src/addons/mod/quiz/tests/behat/quiz_navigation.feature, src/theme/theme.base.scss
This reverts commit 3faa55e489f9d2eea24ca1522296fe31d32beda5.
=> Revert "MOBILE-4339 quiz: Add unanswered questions warning"

src/addons/mod/quiz/tests/behat/quiz_navigation.feature
This is necessary so that MDL-79295 can move forward with the integration.
=> MOBILE-4350: Comment out sequential navigation test

src/core/features/login/tests/behat/basic_usage.feature
This PR should be merged when the Moodle integration branch is merged into main.
=> Mobile 4616

src/addons/mod/assign/tests/behat/marking_workflow.feature
The solution is the same as the one applied in LMS:
https://github.com/moodle/moodle/commit/4ac3f6f8c73276eff99571a61398e6c0003b00d5#diff-50105a659b0aa30e86d54efe05c1b912b08ce2b9cbb94dc98ad308a9a2212177R24
=> MOBILE-4616 assign: Fix behats after change done in MDL-80744

src/core/features/fileuploader/services/fileuploader.ts
Uploading several files in parallel can cause a race condition in the server when trying to insert the directory data in the 'files' table of the DB, in the create_directory function. To avoid that, now files are uploaded 1 by 1 in the same area.
=> MOBILE-4653 core: Fix race condition when uploading files

src/addons/mod/lesson/pages/player/player.scss, src/addons/mod/workshop/components/submission/submission.ts, src/addons/mod/workshop/pages/submission/submission.html
Related to commit f337eebd57d30acc3c1c755bf8b86ab8f4d858fe
=> MOBILE-4653 workshop: Fix submission duplicated in submission page

src/addons/mod/assign/components/submission/submission.ts, src/addons/mod/assign/feedback/comments/component/comments.ts, src/addons/mod/assign/services/assign-sync.ts, src/addons/mod/assign/submission/file/component/file.ts, src/addons/mod/assign/submission/file/services/handler.ts, src/addons/mod/assign/submission/onlinetext/component/onlinetext.ts, src/addons/mod/assign/submission/onlinetext/services/handler.ts
Offline submission will have empty plugin data but submissionstatement should be filled
=> MOBILE-4653 assign: Fix submit for grading in offline

src/addons/mod/data/components/search-modal/search-modal.html, src/addons/mod/data/components/search-modal/search-modal.ts
The template was rendered before the required components were imported.
=> MOBILE-4653 data: Fix template rendering in advanced search

src/core/components/bs-tooltip/bs-tooltip.ts, src/core/components/bs-tooltip/core-bs-tooltip.html, src/core/components/bs-tooltip/core-bs-tooltip.scss, src/core/directives/format-text.ts, src/core/services/utils/dom.ts, src/core/singletons/bootstrap.ts, src/theme/components/ion-modal.scss
Depends on https://github.com/moodlehq/moodleapp/pull/4499
=> Mobile 4834 Support Bootstrap 5 Collapse, Accordion and Modals
