www/addons/coursecompletion/services/handlers.js

They are not checking correctly if completion is disabled at course
level, this is making the app to do an extra WS request for each course
when displaying "My courses"

MOBILE-1896 compleiton: Fix plugin enabled checks

---

www/addons/mod/feedback/controllers/respondents.js
www/addons/mod/forum/controllers/discussions.js
www/addons/mod/glossary/controllers/index.js
www/addons/participants/controllers/list.js
www/core/components/course/controllers/sections.js

If the objects are modified inside the controller, Ionic will open the left state again when loading the split view content.

MOBILE-2103 splitview: Clone state params object in split view states

---

www/core/directives/formattext.js

The new regex matches Moodle vimeo filter one

MOBILE-2313 formattext: Use correct regex for Vimeo

---

www/addons/mod/lti/controllers/index.js
www/addons/mod/lti/services/lti.js
www/addons/mod/lti/templates/index.html

We use now only the emergencyCache to avoid repeat values like the
oauth_nonce (that it is usually a timestamp and should be unique
between requests).
Refresh options could be removed, but I think is ok to keep it for
debugging.

MOBILE-2252 lti: Avoid cache when launching

---

src/core/course/pages/section/section.ts

core_enrol_get_users_courses does not return displayname before MDL-63523,
which causes the page title to revert to fullname after the course
has fully loaded.

MOBILE-2721 Keep existing displayname if not set

---

src/core/course/components/format/core-course-format.html
src/core/course/components/format/format.ts
src/core/course/components/module-completion/module-completion.ts
src/core/course/components/module/core-course-module.html
src/core/course/components/module/module.ts
src/core/course/pages/section/section.html
src/core/course/pages/section/section.ts

Now that completion data includes valueused, we can refresh the page in
response to a completion change only when valueused is true.
It is is false, we can update the checkbox and
progress bar client-side.

MOBILE-2746 UX: Only refresh page if completion value is used

---

src/core/course/pages/section/section.html
src/core/course/pages/section/section.ts
src/core/course/providers/helper.ts
src/core/course/providers/options-delegate.ts

This allows addons to add items to the course menu. The items work
in the same way as other course options, except that instead of
appearing as a tab, they appear as an option in the course menu.

MOBILE-2906 Add course option type that appears in menu

---

src/providers/ws.ts

We add a redundant &wsfunction=web_service_method_name to the URL
for web service requests, so that it is easier to find the call you
are interested in when debugging using brower tools.
Similarly, we add info= to calls to lib/ajax/service.php, matching what
is done in Moodle web application JavaScript.

MOBILE-2951 web-services: make it easier to debug web service calls

---

src/addon/messages/pages/discussion/discussion.scss
src/addon/mod/lesson/pages/player/player.scss
src/app/app.scss
src/components/ion-tabs/ion-tabs.scss
src/components/tabs/tabs.scss
src/core/block/components/course-blocks/course-blocks.scss

Ionic sets the "contain" CSS property to some elements. This enables CSS
containment, which changes how elements are positioned and sized, breaking
fixed positioned elements, iframes in full screen mode, subtitle menus in
videos and potentially more things. CSS containment is not supported in iOS
and Android 4.4, so it can introduce inconsistencies across devices.

MOBILE-3042 styles: Disable all CSS contianment rules

---

src/core/siteplugins/providers/helper.ts

If displaydata is not specified in mobile.php for a block, it
did not work due to a JavaScript error.

MOBILE-3140 Blocks: Make blocks work if displaydata not specified

---

src/core/siteplugins/components/plugin-content/plugin-content.ts

For pages served via a site plugin, if the page has never been viewed
(there is no cached version) then if you try to view the page when
offline, the navigation broke because page loading never finished.
This change makes it finish page loading (with a blank page) if it
shows the error about failing to load it.

MOBILE-3180 Site plugins: Plugin pages offline can break navigation

---

config.xml
package-lock.json
package.json

The 2.2.0 version causes the input text to be behind the keyboard when sending messages.

MOBILE-3213 core: Revert keyboard plugin to 2.1.3

---

src/core/filter/providers/helper.ts

Each contextLevel overrode the other contextLevels, causing some cached data to be lost

MOBILE-3269 filter: Fix memory cache issue with contextLevels

---

config.xml

There is a Cordova bug that prevents some config changes made by plugins to be applied to manifest. For now we'll have to replicate them in our config.xml.

MOBILE-3401 config: Fix some plugins in Android

---

src/providers/sites.ts

The extra parameter can be used by Moodle to avoid throwing an error
in server logs because other parameters e.g. username are not supplied.

MOBILE-3556 Login: Send extra parameter on token.php check

---

src/addons/calendar/pages/edit-event/edit-event.html
src/addons/mod/data/fields/date/component/addon-mod-data-field-date.html

This is a temporary fix, it should be considered further in MOBILE-3784

MOBILE-3320 calendar: Fix timezone in ion-datetime

---

src/addons/calendar/components/filter/filter.ts
src/addons/messages/pages/search/search.html
src/addons/mod/data/services/data-helper.ts
src/addons/mod/forum/components/discussion-options-menu/discussion-options-menu.html
src/addons/mod/forum/components/edit-post/edit-post.html
src/addons/mod/forum/components/index/index.html
src/addons/mod/forum/components/post/post.html
src/addons/mod/forum/pages/discussion/discussion.html
src/addons/mod/forum/pages/new-discussion/new-discussion.html
src/core/features/block/classes/base-block-handler.ts
src/core/features/block/services/block-delegate.ts
src/core/features/course/pages/contents/contents.html
src/core/features/tag/pages/index/index.html
src/core/features/user/pages/about/about.html
src/core/features/user/pages/profile/profile.html

The last commit in particular fixes database templates, that were broken in [this commit](https://github.com/moodlehq/moodleapp/commit/49f6cc56e55a503c696102946f73a4b3b96be0f5#diff-23f88613aff553b7ff16c3c2f1541eca6be80af122be539ce36247a0b6fec225R661), and I think it was a mistake done by using global replacements.
The fix may undo the a11y improvements that were introduced in that commit, but the proper solution would involve making a regex that captures the whole link (including contents and closing tag) and replacing it for a button. I think that's too risky at this stage, so it's better to just revert it to what we had before and revisit this issue later on, when we review a11y for the database activity.

MOBILE-3320: Fix regressions

---

package.json

As documented in https://docs.moodle.org/dev/Using_the_Moodle_App_in_a_browser#Configuring_the_default_browser

MOBILE-3833 DX: Configure default browser

---

package.json

Added this script in order to go in line with the documentation at https://docs.moodle.org/dev/Acceptance_testing_for_the_Moodle_App

MOBILE-3833 DX: Configure `serve:test` script

---

angular.json
package.json
webpack.config.js

I configured optimization in the testing build in order to make it behave as similar as possible to production. Before this change, site plugins were broken but Behat tests were passing. This should be used mostly in CI anyways, developers running tests locally should be using the `serve:test` command instead.

MOBILE-3833: Fix JIT for site plugins

---

src/app/app.component.ts
src/core/initializers/initialize-urlscheme.ts

It seems the function was declared too late, when it had already been called.

MOBILE-4126 ios: Fix handleOpenURL when app is closed

---

src/core/directives/external-content.ts

This fixes an issue when rendering images using directly the local URL (e.g. in image viewer)

MOBILE-4081 external-content: Set attribute for untreated urls

---

src/core/features/block/components/side-blocks-tour/side-blocks-tour.html
src/core/features/course/components/course-index-tour/course-index-tour.html
src/core/features/mainmenu/components/user-menu-tour/user-menu-tour.html
src/core/features/usertours/services/user-tours.ts

Following the same strategy as Ionic's built-in overlays https://github.com/ionic-team/ionic-framework/blob/1b30fc97d33e761866b4bcf7518efcdeb753032d/core/src/utils/overlays.ts#L388..L401

MOBILE-4065 a11y: Hide pages under user tours

---

src/addons/filter/mediaplugin/classes/videojs-ogvjs.ts
src/addons/filter/mediaplugin/services/handlers/mediaplugin.ts
src/addons/filter/mediaplugin/services/videojs.ts
src/addons/filter/mediaplugin/utils/videojs.ts
src/core/classes/element-controllers/MediaElementController.ts
src/core/singletons/events.ts
src/index.html
src/polyfills.ts

VideoJS is only used in some pages, and only in iOS, so it'd be best to lazy load it as necessary.
Other than that, I removed the `id` from the event payload because it's not being used, so it's possible it's dead code from previous versions.

MOBILE-4239 mediaplugin: Lazy load videojs

---

src/addons/mod/assign/tests/behat/marking_workflow.feature

The reason is that the steps to mark submissions in LMS don't work in older sites, they need to be different

MOBILE-4281 assign: Limit marking workflow behats to 4.0+

---

package-lock.json
package.json

It is needed by cordova-plugin-qrscanner
This reverts commit e8e31349fcd90e735bd247172ebc9777eaad1d98.

MOBILE-4215 cordova: Add cordova-plugin-androidx-adapter again

---

package-lock.json
package.json

The official plugin doesn't work in Android with API 33

MOBILE-4215 cordova: Use fork of cordova-plugin-camera

---

src/core/classes/items-management/list-items-manager.ts

The previous implementation was running into some race conditions that caused it to scroll back to the previously selected item sometimes.

MOBILE-4270 core: Fix list items auto-scroll

---

src/addons/mod/lesson/tests/behat/numerical_decimal_separator-311.feature
src/addons/mod/lesson/tests/behat/numerical_decimal_separator.feature

Headless mode was using a smaller window size which caused the course index to be hidden by default, and that's what made tests fail.

MOBILE-4362: Fix tests in headless mode

---

.github/workflows/testing.yml
Dockerfile
cordova-plugin-moodleapp/.gitignore
cordova-plugin-moodleapp/package-lock.json
cordova-plugin-moodleapp/package.json
cordova-plugin-moodleapp/plugin.xml
cordova-plugin-moodleapp/scripts/build.js
cordova-plugin-moodleapp/scripts/copy-javascript.js
cordova-plugin-moodleapp/scripts/templates/cordova-plugin.js
cordova-plugin-moodleapp/src/android/SystemUI.java
cordova-plugin-moodleapp/src/ts/index.ts
cordova-plugin-moodleapp/src/ts/plugins/SystemUI.ts
cordova-plugin-moodleapp/tsconfig.json
cordova-plugin-moodleapp/types/index.d.ts
package-lock.json
package.json
src/core/features/native/services/native.ts
tsconfig.app.json
tsconfig.json
tsconfig.test.json

This PR only implements the plugin, but it's not actually used anywhere in the app (this will be implemented in a follow-up PR). It can be used like this:
```ts
CoreNative.plugin('systemUI')?.setNavigationBarColor('#ff00ff');
```
Also, keep in mind that I just copied the code from [fagundes/cordova-plugin-navigationbar](https://github.com/fagundes/cordova-plugin-navigationbar/blob/master/src/android/NavigationBar.java), but presumably that has to be updated in some way (that's the whole reason why we're doing our own plugin to begin with).
Finally, I wasn't able to test this in an emulator because I didn't manage to display the navigation bar :/. But I tried with a real device and it worked.

MOBILE-4331: Implement native plugin

---

src/addons/mod/chat/pages/session-messages/session-messages.ts
src/addons/mod/chat/pages/sessions/sessions.ts
src/addons/mod/chat/services/chat.ts

This could be integrated already, but it won't work until [MDL-74568](https://tracker.moodle.org/browse/MDL-74568) is integrated in core, so I'm leaving it as a draft until then.

MOBILE-4048 chat: Log sessions view events

---

src/core/classes/site.ts
src/core/components/recaptcha/recaptcha.ts
src/core/features/mainmenu/services/mainmenu.ts
src/core/features/siteplugins/services/siteplugins.ts
src/core/services/lang.ts
src/core/services/sites.ts
src/core/services/utils/url.ts
src/core/services/ws.ts

For child parents, such as pt-br, the app format and LMS format are different (in the LMS it would be pt_br). So application lang should be formatted before being sent to webservices and other contexts.

MOBILE-4390 lang: Format LMS lang

---

src/addons/mod/wiki/components/index/index.ts
src/core/features/course/tests/behat/basic_usage.feature

This commit avoids a redundant error and also allows the create button to appear if the user has permissions to create the first page

MOBILE-4401 wiki: Fix selected subwiki when wiki is empty

---

src/core/directives/collapsible-header.ts
src/core/singletons/dom.ts

When the system font size is increased, the CSS values and computed style values are not equivalent. So we have to take that into account when mirroring styles to the floating title.

MOBILE-4189 core: Fix collapsible header zoom

---

src/core/features/search/classes/global-search-results-source.ts
src/core/features/search/services/global-search.ts

They've been removed because they are not respecting category filters. In the LMS it's the expected behaviour because they use category tabs instead, but that is not correct in the app.

MOBILE-3371 search: Remove top results

---

.github/workflows/testing.yml
angular.json
package-lock.json
package.json
patches/check-es-compat+3.1.0.patch
src/polyfills.ts

The check-es-compat patch can be removed if the following PR is resolved: https://github.com/robatwilliams/es-compat/pull/86

MOBILE-3947 ng: Update polyfills

---

src/testing/services/behat-runtime.ts

This step was also working for other elements such as ion-alert before upgrading to ionic 7, so we should keep the same behaviour.

MOBILE-3947 behat: Fix close popup step

---

src/core/features/login/tests/behat/signup.feature

This test started failing after MDL-72703 was integrated

MOBILE-4470 behat: Fix signup tests

---

src/addons/mod/quiz/pages/player/player.ts

This is consistent with the LMS which has a "return to attempt" button. It also fixes the behaviour that users would expect, given that the buttons in the side navigation for the current page are not disabled in the summary.

MOBILE-4350 quiz: Allow navigating from sequential summary

---

src/core/features/grades/services/grades-helper.ts
src/core/services/utils/text.ts

Right now, this menu is only used to link to the "Grade Analysis" because this link was removed from the LMS after some recent changes. But the mobile app never had this link, so we can safely remove the menu for now.

MOBILE-4569 grades: Remove actions menu

---

src/addons/mod/quiz/pages/attempt/attempt.html
src/addons/mod/quiz/pages/review/review.html
src/addons/mod/quiz/pages/review/review.ts

This makes it consistent with the way it works in the LMS, we're also relying on attempt.sumgrades because grade item marks are never null. See MDL-81599.

MOBILE-4553 quiz: Hide ungraded marks

---

src/core/directives/collapsible-header.ts

There were some scenarios were the scrollingHeight was recalculated, but the listeners weren't using the latest value and thus causing the wrong behaviour.

MOBILE-4470 core: Fix collapsible header scrolling

---

src/addons/block/timeline/components/timeline/timeline.ts

This may have been introduced by mistake in commit https://github.com/moodlehq/moodleapp/commit/0f5416e2f0750da7aa5c015ffcfb2d12fd87ae32. Looking at improvements introduced in 4.0, past courses were never filtered out but the UI says "No in-progress courses" when empty; that may have caused the confusion.

MOBILE-4470 timeline: Avoid filtering past courses

---

src/core/components/mod-icon/mod-icon.html
src/core/components/mod-icon/mod-icon.ts

This change is necessary because some icons weren't updated properly inside of components using OnPush (e.g. course-storage page).

MOBILE-4470 core: Refactor mod-icon to use signals

---

src/addons/calendar/tests/behat/create_events.feature
src/core/features/login/pages/reconnect/reconnect.ts
src/core/features/styles/services/styles.ts
src/core/singletons/events.ts

This reverts commit f75bfd39d15ae8efb9907cfa73474a1029da47c8.
This change caused another problem, so I opened an issue to look at it for 4.5: https://tracker.moodle.org/browse/MOBILE-4606

MOBILE-4470 remotethemes: Revert fix styles not loaded in offline

---

src/addons/mod/assign/components/submission-plugin/submission-plugin.ts

Changes to the allowOffline property of AddonModAssignSubmissionPluginComponent were not being detected and passed to the submission plugin component.

MOBILE-3893 assign: Fix editing files offline

---

src/addons/storagemanager/pages/course-storage/course-storage.html

The download page didn't filter by visibility like it's done in the course page, and this caused errors because there was no handlerData in qbank

MOBILE-4807 course-storage: Fix error caused by qbank activity

---

src/core/services/ws.ts

If the certificate isn't trusted in Android, the error response doesn't contain headers so the code threw an exception and the proper error message was lost.

MOBILE-4842 ws: Fix bug when SSL error in Android

---

src/addons/mod/h5pactivity/tests/behat/overview.feature
src/addons/mod/quiz/tests/behat/overview.feature

This was changed in [MDL-86520](https://moodle.atlassian.net/browse/MDL-86520). The behats will fail until that issue's code is moved to the moodle/moodle repository.
[MDL-86520]: https://moodle.atlassian.net/browse/MDL-86520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOBILE-4770 overview: Adapt behats to new average count

---

local_moodleappbehat/tests/behat/behat_app_helper.php

The press action in Behat was sometimes throwing the error "Promise was collected". The cause of this error is unclear, but it can be prevented by adding an explicit await in the executed JS code.

MOBILE-4842 behat: Fix error in @core_reminders tests

---

src/core/directives/format-text.ts
src/core/singletons/dom.ts
src/core/singletons/tests/text.test.ts
src/core/singletons/text.ts

There was a problem with rendering emoji on iOS on message discussions. Those emojis were not rendered until something change in the page.

MOBILE-4902 format-text: Use signals on format-text to fix render
